"""quotes”
flask db migrate -m quotes”

Revision ID: 078d7f1918f6
Revises: 4bd5f90dd3a9
Create Date: 2020-12-02 14:37:42.516082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078d7f1918f6'
down_revision = '4bd5f90dd3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    # ### end Alembic commands ###
