"""boards table

Revision ID: 793611cc1e4d
Revises: 1b96f0468ede
Create Date: 2020-11-06 21:47:04.893489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793611cc1e4d'
down_revision = '1b96f0468ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_title'), 'board', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_title'), table_name='board')
    op.drop_table('board')
    # ### end Alembic commands ###
